services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paystack-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - FRONTEND_URL=http://localhost
    restart: unless-stopped
    networks:
      - paystack-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://13.41.246.221:3000/api/payment
        - VITE_PAYSTACK_PUBLIC_KEY=${VITE_PAYSTACK_PUBLIC_KEY}
    container_name: paystack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - paystack-network

networks:
  paystack-network:
    driver: bridge
